name: Setup/Cache Env
description: 'Sets up and caches a Python env using Conda. Falls back to pip only if needed.'

runs:
 using: composite
 steps:
   - name: Set up Miniconda
     uses: conda-incubator/setup-miniconda@v2
     with:
       python-version: "3.13"
       auto-activate-base: false

   - name: Create/Update Conda Env
     shell: bash
     run: |
       if conda env list | grep -q '^p5[[:space:]]'; then
         conda env update --name p5 --file requirements/environment.yml --prune
       else
         conda env create --name p5 --file requirements/environment.yml
       fi

   - name: Install extra pip requirements
     shell: bash
     run: |
       for file in requirements/requirements*.txt; do
         [[ -f "$file" ]] && conda run -n p5 pip install -r "$file"
       done