# .github/actions/setup_env/action.yaml
name: "setup_env"
description: "Create and activate the Conda environment via mamba"
inputs:
 environment-file:
   description: "Path to the .yml or .lock.yml file"
   required: true
   default: "requirements/environment.yml"
runs:
 using: "composite"
 steps:
   - name: Install Miniconda
     uses: goanpeca/setup-miniconda@v1
     with:
       python-version: "3.13"
       auto-activate-base: false

   - name: Install Mamba
     run: |
       conda install --yes mamba -n base -c conda-forge

   - name: Create environment
     run: |
       mamba env create --yes --file "${{ inputs.environment-file }}" -n p5

   - name: Persist environment
     run: |
       echo "$HOME/miniconda3/envs/p5/bin" >> $GITHUB_PATH
       echo "CONDA_PREFIX=$HOME/miniconda3/envs/p5" >> $GITHUB_ENV