# .github/actions/setup_env/action.yaml
name: "setup_env"
description: "Install Miniconda, create the p5 env via Mamba, then pip-install extra wheels"
inputs:
environment-file:
  description: "Path to .yml or .lock.yml file"
  required: true

runs:
using: "composite"
steps:
  - name: Install Miniconda
    uses: goanpeca/setup-miniconda@v1
    with:
      python-version: "3.13"
      auto-activate-base: false

  - name: Install Mamba & Conda-lock
    run: |
      conda install --yes -n base -c conda-forge mamba conda-lock

  - name: Create Conda environment
    run: |
      mamba env create --yes \
        --file "${{ inputs.environment-file }}" \
        -n p5

  - name: Add p5 env to PATH
    run: |
      echo "$HOME/miniconda3/envs/p5/bin" >> $GITHUB_PATH
      echo "CONDA_PREFIX=$HOME/miniconda3/envs/p5" >> $GITHUB_ENV

  - name: Pip-install extra wheels
    run: |
      pip install --requirement requirements/requirements.txt