# .github/workflows/ci.yaml
name: CI

on:
 push:
   branches: [ main ]
 pull_request:
   branches: [ main ]

jobs:
 test:
   strategy:
     matrix:
       include:
         - os: ubuntu-latest
           lockfile: conda-linux-64.lock.yml
         - os: macos-latest
           lockfile: conda-osx-arm64.lock.yml
   runs-on: ${{ matrix.os }}
   steps:
     - name: Checkout code
       uses: actions/checkout@v3

     - name: Setup environment
       uses: ./.github/actions/setup_env
       with:
         environment-file: ${{ matrix.lockfile }}

     - name: Run tests
       run: pytest --maxfail=1 --disable-warnings -q